[tool.poetry]
name = "pyflowcl"
version = "1.1.0"
description = "Cliente para comunicacion con flowAPI-3 de flow.cl"
authors = ["Mario Hernandez <yo@mariofix.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/mariofix/pyflowcl"
documentation = "https://pyflowcl.readthedocs.io/es/latest/index.html"
classifiers=[
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
packages = [{include = "pyflowcl"}]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.25.1"
openapi3 = {git = "https://github.com/Dorthu/openapi3.git", rev = "master"}
python-fsutil = "^0.7.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
coverage = "*"
black = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
